package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-730040-redhat-00001
  * 2019-11-21T12:48:22.365+01:00
 * Generated source version: 3.2.7.fuse-730040-redhat-00001
 *
 */
@WebServiceClient(name = "OnlineMessagesService",
                  wsdlLocation = "file:/C:/Users/ddambrosi/Documents/documenti/bennet/OnlineMessagesService.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class OnlineMessagesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "OnlineMessagesService");
    public final static QName OnlineMessagesServiceSoap12 = new QName("http://tempuri.org/", "OnlineMessagesServiceSoap12");
    public final static QName OnlineMessagesServiceSoap = new QName("http://tempuri.org/", "OnlineMessagesServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/ddambrosi/Documents/documenti/bennet/OnlineMessagesService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OnlineMessagesService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/ddambrosi/Documents/documenti/bennet/OnlineMessagesService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OnlineMessagesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OnlineMessagesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OnlineMessagesService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OnlineMessagesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OnlineMessagesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OnlineMessagesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OnlineMessagesServiceSoap
     */
    @WebEndpoint(name = "OnlineMessagesServiceSoap12")
    public OnlineMessagesServiceSoap getOnlineMessagesServiceSoap12() {
        return super.getPort(OnlineMessagesServiceSoap12, OnlineMessagesServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnlineMessagesServiceSoap
     */
    @WebEndpoint(name = "OnlineMessagesServiceSoap12")
    public OnlineMessagesServiceSoap getOnlineMessagesServiceSoap12(WebServiceFeature... features) {
        return super.getPort(OnlineMessagesServiceSoap12, OnlineMessagesServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns OnlineMessagesServiceSoap
     */
    @WebEndpoint(name = "OnlineMessagesServiceSoap")
    public OnlineMessagesServiceSoap getOnlineMessagesServiceSoap() {
        return super.getPort(OnlineMessagesServiceSoap, OnlineMessagesServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnlineMessagesServiceSoap
     */
    @WebEndpoint(name = "OnlineMessagesServiceSoap")
    public OnlineMessagesServiceSoap getOnlineMessagesServiceSoap(WebServiceFeature... features) {
        return super.getPort(OnlineMessagesServiceSoap, OnlineMessagesServiceSoap.class, features);
    }

}
